### ISSUE TITLE
Compound Variants in React

### ISSUE THREAD

**Issue by natethegreat5413** [fgnass/classname-variants#7]
I'm not able to have multiple variants work within the compoundVariants array.  The only way I am able to get this to work is throwing an important tag on the bg-transparent which I'd like to avoid doing.  

Here's my code you can throw into a sandbox.

`import { variantProps } from "classname-variants/react";`

`const buttonProps = variantProps({`
  `base: "flex flex-row justify-center items-center text-center text-white py-1 px-3 rounded-md font-medium text-xs min-h-[1.875rem] w-fit",`
`  variants: {`
  `  color: {`
    `  primary: "bg-violet-500",`
      `positive: "bg-green-600",`
      `warning: "bg-orange-500",`
      `negative: "bg-red-500"`
    `},`
    `outlined: {`
     ` true: "border bg-transparent"`
    `}`
  `},`
  `compoundVariants: [`
    `{`
    `  variants: { color: "primary", outlined: true },`
      `className: "text-violet-500 border-violet-500"`
    `},`
    `{`
      `variants: { color: "positive", outlined: true },`
      `className: "text-green-600 border-green-600"`
    `},`
    `{`
      `variants: { color: "warning", outlined: true },`
      `className: "text-orange-500 border-orange-500"`
    `},`
    `{`
      `variants: { color: "negative", outlined: true },`
      `className: "text-red-500 border-red-500"`
    `}`
  `],`
  `defaultVariants: {`
    `color: "positive"`
  `}`
`});`

`const Button = ({ color, outlined, children }) => {`
  `return <div {...buttonProps({ outlined, color })}>{children}</div>;`
`};`

`export default function App() {`
  `return (`
    `<div className="flex items-center gap-2 p-4">`
        `<Button color="primary" outlined>`
          `Click Me!`
        `</Button>`
        `<Button color="positive" outlined>`
          `Click Me!`
        `</Button>`
        `<Button color="warning" outlined>`
          `Click Me!`
     `   </Button>`
       ` <Button color="warning">`
         ` Click Me!`
        `</Button>`
      `</div>`
  `);`
`}`

**Comment by fgnass** [comment]
One possible solution would be this: https://codesandbox.io/s/classname-variants-issue-7-jxvlqu?file=/src/App.tsx

Alternatively you could use CSS variables for a slightly less verbose solution: https://codesandbox.io/s/classname-variants-issue-7-css-vars-hucl68?file=/src/App.tsx

**Comment by natethegreat5413** [comment]
Thanks for that.  One other quick thing.  Is there a way to pass in className as a prop so that I can apply further styles when using the component throughout the app (for positioning an whatnot) without overriding the current styles?

**Comment by fgnass** [comment]
Yes. I've updated https://codesandbox.io/s/classname-variants-issue-7-jxvlqu?file=/src/App.tsx - See the last component which adds `className="shadow-lg"`.
